### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by spinal84**
Please feel free to correct if I have something missed.

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Technically it will no longer receive events from HAL, but rather from udev and other kernel components. HAL is deprecated for a long time, and it's not available on Devuan/Debian.

**Comment by MerlijnWajer** [comment]
BTW: what would be a good way to coordinate, aside from on github issues? irc, mail, mailing listsl, talk.maemo.org? (I mean for you)

**Comment by spinal84** [comment]
spinal.by at gmail dot com

**Comment by MerlijnWajer** [comment]
Thanks for the changed - I removed the comment with the mail addr (I did write it down) :D

**Pull request merged**
